name: Test Vite
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Code
              uses: action/checkoutv3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with: 
                node-version: "18"
            - name: Install dependencies
              run: npm ci
            - name: app-build
              run: npm run build
            - name: app-Test
              run: npm run test